/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2500
    gain: 5.0

/serial_driver:
  ros__parameters:
    timestamp_offset: -0.0025
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/light_detector:
  ros__parameters:
    debug: true
    binary_thres: 100
    light.min_ratio: 0.05
    ignore_classes: ["negative"]
    # 新增卡尔曼滤波参数 —— 控制角度自适应滤波切换
    angle_filter_Q_small: 0.0005    # 静止时过程噪声
    angle_filter_Q_big:   1.0      # 大运动时过程噪声
    angle_filter_R:       0.01     # 角度测量噪声
    motion_gate:
      angle_delta_threshold_deg: 0.06
      pixel_delta_threshold_px: 8.0
      stop_confirm_frames: 3
      default_distance: 1.0
      default_angle: 0.0
      default_stability: 0
      filter_jump_threshold_deg: 1.72
      send_stability_angle_threshold_deg: 3.44
      send_stability_release_angle_threshold_deg: 4.0
      stability_confirm_frames: 3
    # —— 在这里添加 dart_angle_offset —— 
    dart_angle_offset:
      "1": 0.0
      "2": 0.0
      "3": 0.0
      "4": 0.0
      "5": 0.0
      "6": 0.0
      "7": 0.0
      "8": 0.0
      "9": 0.0
    # —— 在这里添加 stability_angle_offset ——
    stability_angle_offset:
      "1": -0.8
      "2": -0.75
      "3": -0.8
      "4": -0.85
      "5": -0.8
      "6": -0.7
      "7": -0.7
      "8": -0.55
      "9": -0.75
